### ISSUE TITLE
로그인 돼 있는데도 홈페이지에 로그인 버튼이 떠 있는 문제

### ISSUE THREAD

**Issue by SausageTaste** [wnwoghd22/jejudo_drone_prototype_web#2]
![Screenshot_20210129-174814_Chrome](https://user-images.githubusercontent.com/23379360/106252997-3e7ead00-625a-11eb-9862-e3da4937453d.jpg)

로그아웃 기능을 추가하는 것도 좋을 것 같음.

**Comment by wnwoghd22** [comment]
이게 auth.currentUser가 null인지 아닌지 체크해서 적당한 컴포넌트를 render하게 되어있는데
새로고침하고나서 auth가 null이 되는 바람에 생기는 문제인 듯 함.

**Comment by SausageTaste** [comment]
새로 고침 안 해도 이렇게 뜨던데.

**Comment by wnwoghd22** [comment]
componentDidMount였나... 그 참조값을 어디서 받아오는지 문제인 것 같음

**Comment by wnwoghd22** [comment]
관찰자 추가해서 해결함.

**Comment by SausageTaste** [comment]
👍
