### ISSUE TITLE
로그인 안 한 채로 예약탭의 날짜를 누르면 오류 발생

### ISSUE THREAD

**Issue by SausageTaste** [wnwoghd22/jejudo_drone_prototype_web#3]
![2021-01-29](https://user-images.githubusercontent.com/23379360/106254565-345dae00-625c-11eb-857d-da89699f9a10.png)

널포인터를 적절하게 처리하지 않아 생긴 것으로 보임.

나의 수업 탭을 눌러도 같은 오류가 발생합니다.

**Comment by wnwoghd22** [comment]
로그인한 상태여야 currentUser 안의 값을 참조할 수 있어서 생기는 문제.
애초에 로그인 안 된 상태에서는 저 탭에 들어갈 수 없게 처리를 하도록 바꿔야 함

**Comment by wnwoghd22** [comment]
문제 고쳤습니다.
로그인 했는지 안 했는지 체크 후 렌더링 하는 것으로 변경

**Comment by SausageTaste** [comment]
예약 탭에서 날짜 클릭하면 백지화면 뜨는 문제는 아직 고쳐지지 않음.

**Comment by wnwoghd22** [comment]
문제 해결. 페이지 이동 후 렌더링이 안 되는 문제가 생겼습니다 ㅠㅠ
