### ISSUE TITLE
rerendering

### ISSUE THREAD

**Issue by wnwoghd22** [wnwoghd22/jejudo_drone_prototype_web#5]
로그인 후 계정 생성 페이지 전환, 달력에서 날짜 선택 후 페이지 전환 시 리액트 렌더링이 되지 않는다.
history.pushState()를 써서 생긴 문제 같다.

**Comment by wnwoghd22** [comment]
route를 써서 해결하긴 했다.
근데 더 효율적인 방법은 없었을까 싶다.

**Comment by SausageTaste** [comment]
뭔 소린지 모르겠다.

**Comment by wnwoghd22** [comment]
리액트의 route 모듈을 쓰면 페이지 전환 및 컴포넌트 렌더링을 손쉽게 처리할 수 있는데, 문제는 어떤 작업을 한 후에 조건에 따라 페이지를 전환하는 기능을 구현하기가 좀 까다로워서... route component 안에 props로 history가 기본으로 내장되어 있고 이걸 쓰면 html tag안에서만이 아니라 일반 javascript 코드에서도 리액트에 최적화된 싱글 페이지 전환을 구현할 수 있음. 지금은 해결하긴 했는데, 좀 지저분해진 느낌이 있어서.
AccountPage의 CreateAcount()가 전부 버튼 하나를 만들기 위한 코드임.
