### ISSUE TITLE
구글 없이 회원가입 할 때, if 블럭과 else 블럭 둘 다 실행됨

### ISSUE THREAD

**Issue by SausageTaste** [wnwoghd22/jejudo_drone_prototype_web#6]
`./web/src/components/login/account.tsx` 파일의 `CreateAccount` 함수(?) 안에 보면 `user` 변수를 갖고 분기를 하는 부분이 있는데.

```ts
...

auth.onAuthStateChanged(user => {
    if(user) {
        ...

        console.log("sign up branch 1");  // 프린팅 코드는 내가 추가한 거임
        console.log(this.state.account);

        postAccount(this.state.account).then(() =>{
            alert('계정이 생성되었습니다.');
            history.push('/');
        })
    } else {
        ...

        auth.createUserWithEmailAndPassword(_email, _password).then(result => {
            ...

            console.log("sign up branch 2");
            console.log(this.state.account);

            postAccount(this.state.account).then(() => {
                alert('계정이 생성되었습니다.');
                history.push('/');
            })
        })
    }
});

...
```

이게 뭔지는 자세히는 모르겠지만, if 부분과 else 부분이 둘 다 실행해야 하는 건 아니라고 생각하는데.

![2021-02-06](https://user-images.githubusercontent.com/23379360/107118079-057db280-68c2-11eb-95ab-d5814e2735dd.png)

위 코드 조각에 보이는 것처럼 콘솔에 프린트 몇 개를 해보니까 두 블럭 다 실행되는 것으로 보임.
이거 버그임?

**Comment by wnwoghd22** [comment]
auth.onAuthStateChanged()는 관찰자로, 로그인 되어있는지 아닌지 그 값의 변화를 실시간으로 감지하는 함수임. 

여기서 문제는 페이지를 렌더링한 직후 잠깐동안 서버로부터 로그인 여부를 확인받는 텀이 생긴다는 건데,
그래서 일단 로그인 되지 않은 것으로 보고 else블럭을 실행시키는 작업 1이 이루어지고,
서버에서 정보가 도착한 순간 if블럭이 실행되는 작업 2가 이루어짐.

콘솔에도 보면 branch2가 먼저 출력되고 branch1이 나중에 출력되는 걸 볼 수 있음.

**Comment by SausageTaste** [comment]
ㅇㅎ 버그는 아니구나

**Comment by wnwoghd22** [comment]
무슨 문제인지 알겠다.

else블럭에서 로그인을 한 후에 프러미스를 쓰는데, 그 때 변화를 잡아서 위에 블럭이 실행되는... 거 같은데. 젠장 어떻게 해야 하지

**Comment by SausageTaste** [comment]
ㅋㅋㅋ 버그냐?
